export const categoriesData = {
    Beauty: {
      image: "/home/woman.svg",
      subcategories: [
        {
          title: "Make Up Artist",
          count: 10,
          Icon: "/explore/health_and_beauty.svg",
          content: [
            {
              id: 1,
              title: "Facial Treatment",
              description: "Relaxing facial treatment for all skin types",
              images: ["/explore/Makeup3 1 1.svg", "/explore/Makeup4 1.svg" ,"/explore/makeup .svg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 10,
              rating: 4.8,
            },
            {
              id: 2,
              title: "Make Up Service",
              description: "Makeup for events and parties",
              images: ["/explore/Makeup4 1.svg","/explore/Makeup3 1 1.svg",  ,"/explore/makeup .svg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 2,
              rating: 4.9,
            },
            {
                id: 3,
                title: "Make Up Service",
                description: "Makeup for events and parties",
                images: ["/explore/makeup .svg ","/explore/Makeup3 1 1.svg", "/explore/Makeup4 1.svg" , "/home/woman.svg"],
                serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
                clientsServed: 6,
                rating: 4.9,
              },
              {
                id: 4,
                title: "Make Up Service",
                description: "Makeup for events and parties",
                images: ["/home/woman.svg","/explore/Makeup3 1 1.svg", "/explore/Makeup4 1.svg" ,"/explore/makeup .svg", ],
                serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
                clientsServed: 5,
                rating: 4.9,
              },
          ],
        },
        {
          title: "Nail Tech",
          count: 4,
          Icon: "/explore/pan_tool.svg",
          content: [
            {
              id: 1,
              title: "Manicure",
              description: "Luxury manicure services",
              images: ["/explore/Nails 1.svg", "/explore/Nail 1 1.svg", "/explore/Nails4 1.svg"],
              serviceArea: "Downtown",
              clientsServed: 10,
              rating: 4.7,
            },
            {
              id: 2,
              title: "Pedicure",
              description: "Relaxing pedicure for healthy feet",
              images: ["/explore/Nail 1 1.svg","/explore/Nails 1.svg",  "/explore/Nails4 1.svg"],
              serviceArea: "Suburban",
              clientsServed: 7,
              rating: 4.6,
            },
            {
                id: 3,
                title: "Pedicure",
                description: "Relaxing pedicure for healthy feet",
                images: ["/explore/Nails4 1.svg","/explore/Nails 1.svg", "/explore/Nail 1 1.svg", ],
                serviceArea: "Suburban",
                clientsServed: 3,
                rating: 4.6,
              },
              {
                id: 4,
                title: "Pedicure",
                description: "Relaxing pedicure for healthy feet",
                images: ["/explore/Nails 1.svg", "/explore/Nail 1 1.svg", "/explore/Nails4 1.svg"],
                serviceArea: "Suburban",
                clientsServed: 5,
                rating: 4.6,
              },
          ],
        },
        {
          title: "Hair Stylist",
          count: 6,
          Icon: "/explore/self_care.svg",
          content: [
            {
              id: 1,
              title: "Hair Styling",
              description: "Trendy haircuts and styling services",
              images: ["/explore/Braids1 1.svg", "/explore/Wig palour 1.svg", "/explore/wig2 1.svg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 18,
              rating: 4.9,
            },
            {
              id: 2,
              title: "Hair Treatment",
              description: "Deep conditioning treatments for your hair",
              images: ["/explore/Wig palour 1.svg","/explore/Braids1 1.svg", , "/explore/wig2 1.svg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 1,
              rating: 4.8,
            },
            {
                id: 3,
                title: "Hair Treatment",
                description: "Deep conditioning treatments for your hair",
                images: ["/explore/wig2 1.svg","/explore/Braids1 1.svg", "/explore/Wig palour 1.svg", ],
                serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
                clientsServed: 11,
                rating: 4.8,
              },
              {
                id: 4,
                title: "Hair Treatment",
                description: "Deep conditioning treatments for your hair",
                images: ["/explore/Braids1 1.svg", "/explore/Wig palour 1.svg", "/explore/wig2 1.svg"],
                serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
                clientsServed: 7,
                rating: 4.8,
              },
          ],
        },
      ],
    },
    "Food & Baking": {
      image: "/home/chef cook.svg",
      subcategories: [
        {
          title: "Private Chef ",
          count: 10,
          content: [
            {
              id: 1,
              title: "Birthday Cake",
              description: "Delicious custom birthday cakes",
              images: ["/explore/food-baking/chef3.svg","/explore/food-baking/Chef dish1.svg", "/explore/food-baking/Chef dish.svg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 30,
              rating: 5.0,
            },
            {
              id: 2,
              title: "Cupcakes",
              description: "Tasty cupcakes for all occasions",
              images: ["/explore/food-baking/Chef dish1.svg","/explore/food-baking/chef3.svg", "/explore/food-baking/Chef dish.svg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 25,
              rating: 4.8,
            },
            {
              id: 3,
              title: "Cupcakes",
              description: "Tasty cupcakes for all occasions",
              images: [ "/explore/food-baking/Chef dish.svg","/explore/food-baking/Chef dish1.svg","/explore/food-baking/chef3.svg",],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 2,
              rating: 4.8,
            },
          ],
        },
        {
          title: "Event Catering Services ",
          count: 4,
          content: [
            {
              id: 1,
              title: "Stew",
              description: "Authentic homemade beef stew",
              images: ["/explore/food-baking/Frame 24814 (1).svg","/explore/food-baking/catering2.svg","/explore/food-baking/Catering1.svg", ],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 18,
              rating: 4.7,
            },
            {
              id: 2,
              title: "Pasta",
              description: "Delicious pasta with special sauce",
              images: ["/explore/food-baking/Catering1.svg", "/explore/food-baking/catering2.svg","/explore/food-baking/Frame 24814 (1).svg",],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 10,
              rating: 4.9,
            },
            {
              id: 3,
              title: "Pasta",
              description: "Delicious pasta with special sauce",
              images: ["/explore/food-baking/Catering1.svg", "/explore/food-baking/catering2.svg","/explore/food-baking/Frame 24814 (1).svg",],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 2,
              rating: 4.9,
            },
          ],
        },
        {
          title: "Baker ",
          count: 4,
          content: [
            {
              id: 1,
              title: "Stew",
              description: "Authentic homemade beef stew",
              images: ["/explore/food-baking/cakes.svg","/explore/food-baking/bread.svg","/explore/food-baking/cakes1.svg", ],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 18,
              rating: 4.7,
            },
            {
              id: 2,
              title: "Pasta",
              description: "Delicious pasta with special sauce",
              images: ["/explore/food-baking/bread.svg","/explore/food-baking/bread.svg","/explore/food-baking/cakes1.svg", ],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 10,
              rating: 4.9,
            },
            {
              id: 3,
              title: "Pasta",
              description: "Delicious pasta with special sauce",
              images: ["/explore/food-baking/cakes1.svg","/explore/food-baking/bread.svg","/explore/food-baking/cakes1.svg", ],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 2,
              rating: 4.9,
            },
          ],
        },
      ],
    },
    "Home Services": {
      image: "/home/Home_servicess1-.svg",
      subcategories: [
        {
          title: "Plumbing",
          count: 5,
          content: [
            {
              id: 1,
              title: "Pipe Repair",
              description: "Fixing damaged pipes",
              images: ["/images/pipe_repair1.jpg", "/images/pipe_repair2.jpg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 140,
              rating: 4.8,
            },
            {
              id: 2,
              title: "Leak Detection",
              description: "Identifying and fixing leaks",
              images: ["/images/leak_detection1.jpg", "/images/leak_detection2.jpg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 160,
              rating: 4.7,
            },
          ],
        },
        {
          title: "Electrical",
          count: 3,
          content: [
            {
              id: 1,
              title: "Wiring Services",
              description: "Complete electrical rewiring",
              images: ["/images/wiring1.jpg", "/images/wiring2.jpg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 130,
              rating: 4.8,
            },
            {
              id: 2,
              title: "Lighting Installation",
              description: "Installation of light fixtures",
              images: ["/images/lighting1.jpg", "/images/lighting2.jpg"],
              serviceArea: "Lekki 1, Lekki 2, VI, Ikoyi",
              clientsServed: 120,
              rating: 4.9,
            },
          ],
        },
      ],
    },
    "Event Planning": {
      image: "/home/Camera1.svg",
      subcategories: [
        {
          title: "Event Coordination",
          count: 8,
          content: [
            {
              id: 1,
              title: "Corporate Events",
              description: "Planning and organizing corporate gatherings",
              images: ["/images/corporate1.jpg", "/images/corporate2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 220,
              rating: 4.9,
            },
            {
              id: 2,
              title: "Weddings",
              description: "Complete wedding planning services",
              images: ["/images/wedding1.jpg", "/images/wedding2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 300,
              rating: 5.0,
            },
          ],
        },
      ],
    },
    "Personal Care": {
      image: "/home/gym.svg",
      subcategories: [
        {
          title: "Event Coordination",
          count: 8,
          content: [
            {
              id: 1,
              title: "Corporate Events",
              description: "Planning and organizing corporate gatherings",
              images: ["/images/corporate1.jpg", "/images/corporate2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 220,
              rating: 4.9,
            },
            {
              id: 2,
              title: "Weddings",
              description: "Complete wedding planning services",
              images: ["/images/wedding1.jpg", "/images/wedding2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 300,
              rating: 5.0,
            },
          ],
        },
      ],
    },
    "Tech Support": {
      image: "/home/Laptop.svg",
      subcategories: [
        {
          title: "Event Coordination",
          count: 8,
          content: [
            {
              id: 1,
              title: "Corporate Events",
              description: "Planning and organizing corporate gatherings",
              images: ["/images/corporate1.jpg", "/images/corporate2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 220,
              rating: 4.9,
            },
            {
              id: 2,
              title: "Weddings",
              description: "Complete wedding planning services",
              images: ["/images/wedding1.jpg", "/images/wedding2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 300,
              rating: 5.0,
            },
          ],
        },
      ],
    },
    "Handy Man": {
      image: "/home/hometech.png",
      subcategories: [
        {
          title: "Event Coordination",
          count: 8,
          content: [
            {
              id: 1,
              title: "Corporate Events",
              description: "Planning and organizing corporate gatherings",
              images: ["/images/corporate1.jpg", "/images/corporate2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 220,
              rating: 4.9,
            },
            {
              id: 2,
              title: "Weddings",
              description: "Complete wedding planning services",
              images: ["/images/wedding1.jpg", "/images/wedding2.jpg"],
              serviceArea: "Nationwide",
              clientsServed: 300,
              rating: 5.0,
            },
          ],
        },
      ],
    },
  };
  